### ISSUE TITLE
Question about Promtail

### ISSUE THREAD

**Issue by pbrissaud** [ViaQ/loki-operator#90]
Hi, 

First of all, I would like to thank you for your initiative of building an operator for Loki ! 

The company in which I work is in a logic of using as many Kubernetes operators as possible and, for now, we have to use the loki-stack helm chart to provide a logging stack.

Do you have any plans to add a Promtail CRD in this operator ? 

Best regards.

**Comment by periklis** [comment]
@pbrissaud The operator is first and foremost dedicated to Loki and TBH we call it LokiStack, because it includes a gateway for OIDC authn and OPA/static-based authz in front of Loki. We don't plan to add promtail, because the design philosophy is to sharpen the focus on operating Loki as a store and not a entire logging stack from collection to store.

**Comment by pbrissaud** [comment]
Thanks for your quick answer ;  I understand your design philosophy.  I will look using Fluentbit/Fluentd with [logging-operator](https://github.com/banzaicloud/logging-operator) to scrape the logs and output them into Loki.
